#!/usr/bin/env bash

HOME='/home/vagrant'

if [[ ! $(id vagrant) ]]; then
  echo "You must run $0 inside your Vagrant environment"
  exit 1
fi

echo 'cd /vagrant' >> ${HOME}/.bash_profile

# Change prompt name to {{ cookiecutter.devenv_name }}
echo 'export PS1=" \033[1;34m{{ cookiecutter.devenv_name }}\033[0m \033[1;31m$ \033[0m"' >> ${HOME}/.bash_profile

# Add local to PATH
echo 'export PATH=$PATH:/vagrant/local' >> ${HOME}/.bash_profile

[ ! -d /vagrant/logs ] && mkdir -p /vagrant/logs

echo "- - - Installing system dependencies - - -"
sudo yum install -q -y git GitPython PyYAML python-devel python-pip python-jinja2 supervisor

yum install -y git

#add helpful aliases
echo "source /vagrant/local/add-aliases.sh" >> ${HOME}/.bash_profile

# Put together a supervisor config
echo "- - - Starting Supervisord - - -"
sudo systemctl start supervisord >/dev/null 2>&1
sudo systemctl enable supervisord >/dev/null 2>&1
sudo chown -R vagrant:vagrant /etc/supervisord.d/

# Set up applications
#echo "- - - Configuring applications - - -"
#sudo -i -u vagrant python /vagrant/local/setup-apps

# Load supervisor config and start applications
echo "- - - Starting services - - -"
sudo supervisorctl reload >/dev/null

echo -e 'Host github.com\n\tStrictHostKeyChecking no\n' >> /home/vagrant/.ssh/config
